#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
version=`wget -O - http://ewr.edge.kernel.org/fedora-buffet/fedora/linux/development/ | sed -n '/<a href="[0-9]*\/">[0-9]*\/<\/a>/ s/[^0-9]*//p' | dd bs=2 count=1`
kernel=`wget -O - http://ewr.edge.kernel.org/fedora-buffet/fedora/linux/development/$version/Everything/x86_64/os/Packages/k/ | grep kernel-core | dd bs=21 skip=1 | sed 's/\.rpm.*//'`

if ! echo `whoami` | grep -Fqx root
then
  echo 'Must be root.'
  exit
fi

if [ -f /usr/bin/rpm2cpio ]
then
  cd ~
  wget -O kernel-core-$kernel.rpm http://ewr.edge.kernel.org/fedora-buffet/fedora/linux/development/$version/Everything/x86_64/os/Packages/k/kernel-core-$kernel.rpm
  wget -O kernel-modules-$kernel.rpm http://ewr.edge.kernel.org/fedora-buffet/fedora/linux/development/$version/Everything/x86_64/os/Packages/k/kernel-modules-$kernel.rpm
  wget -O kernel-modules-extra-$kernel.rpm http://ewr.edge.kernel.org/fedora-buffet/fedora/linux/development/$version/Everything/x86_64/os/Packages/k/kernel-modules-extra-$kernel.rpm
  wget -O kernel-modules-internal-$kernel.rpm http://ewr.edge.kernel.org/fedora-buffet/fedora/linux/development/$version/Everything/x86_64/os/Packages/k/kernel-modules-internal-$kernel.rpm
  mkfifo cpio.exc
  echo -n ./usr/* > cpio.exc & rpm2cpio kernel-core-$kernel.rpm | cpio -D / -uidmE cpio.exc
  echo -n ./lib/* > cpio.exc & rpm2cpio kernel-core-$kernel.rpm | cpio -D /usr -uidmE cpio.exc
  rpm2cpio kernel-modules-$kernel.rpm | cpio -D /usr -uidm
  echo -n ./etc/* > cpio.exc & rpm2cpio kernel-modules-extra-$kernel.rpm | cpio -D / -uidmE cpio.exc
  echo -n ./lib/* > cpio.exc & rpm2cpio kernel-modules-extra-$kernel.rpm | cpio -D /usr -uidmE cpio.exc
  rpm2cpio kernel-modules-internal-$kernel.rpm | cpio -D /usr -uidm
  rm -f cpio.exc
  ln /lib/modules/$kernel/vmlinuz /boot/vmlinuz-$kernel || cp /lib/modules/$kernel/vmlinuz /boot/vmlinuz-$kernel
  ln /lib/modules/$kernel/System.map /boot/System.map-$kernel || cp /lib/modules/$kernel/System.map /boot/System.map-$kernel
  ln /lib/modules/$kernel/config /boot/config-$kernel || cp /lib/modules/$kernel/config /boot/config-$kernel
else
  echo 'You do not have rpm2cpio installed. Install rpm2cpio and try again.'
  exit
fi

if [ -f /boot/vmlinuz-$kernel ] && [ -f /boot/System.map-$kernel ] &&
   [ -f /boot/config-$kernel ] && file /boot/vmlinuz-$kernel | \
   grep -Fq 'Linux kernel x86 boot executable bzImage' && file /boot/System.map-$kernel | \
   grep -Fq 'ASCII text' && file /boot/config-$kernel | \
   grep -Fq 'Linux make config build file'
then
  echo 'Everything is OK. Finishing installation...'
  update-initramfs -ck $kernel
  grub-mkconfig -o /boot/grub/grub.cfg
  ln -fs boot/vmlinuz-$kernel /vmlinuz
  ln -fs boot/initrd.img-$kernel /initrd.img
  rm -f kernel*.rpm
  echo 'Installation is complete! Type in (as root) "shutdown -r now" to restart.'
else
  echo 'Installation aborted due to missing or corrupted files! Try again!'
fi
