#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
host="http://mirrors.edge.kernel.org/fedora-buffet/fedora/linux/development/rawhide/Everything/x86_64/os/Packages"
kernel="`wget -O - $host/k/ | grep kernel-core | dd bs=21 skip=1 | sed 's/\.rpm.*//'`"

[ "`whoami`" != "root" ] && echo Must be root. && exit -1

if [ -f /usr/bin/rpm2cpio ]
then
  cd ~
  wget -O kernel-core-$kernel.rpm $host/k/kernel-core-$kernel.rpm
  wget -O kernel-modules-$kernel.rpm $host/k/kernel-modules-$kernel.rpm
  wget -O kernel-modules-extra-$kernel.rpm $host/k/kernel-modules-extra-$kernel.rpm
  wget -O kernel-modules-internal-$kernel.rpm $host/k/kernel-modules-internal-$kernel.rpm
  mkfifo cpio.exc
  echo -n ./usr/* > cpio.exc & rpm2cpio kernel-core-$kernel.rpm | cpio -D / -uidmE cpio.exc
  echo -n ./lib/* > cpio.exc & rpm2cpio kernel-core-$kernel.rpm | cpio -D /usr -uidmE cpio.exc
  rpm2cpio kernel-modules-$kernel.rpm | cpio -D /usr -uidm
  echo -n ./etc/* > cpio.exc & rpm2cpio kernel-modules-extra-$kernel.rpm | cpio -D / -uidmE cpio.exc
  echo -n ./lib/* > cpio.exc & rpm2cpio kernel-modules-extra-$kernel.rpm | cpio -D /usr -uidmE cpio.exc
  rpm2cpio kernel-modules-internal-$kernel.rpm | cpio -D /usr -uidm
  rm -f cpio.exc
  ln /lib/modules/$kernel/vmlinuz /boot/vmlinuz-$kernel || cp /lib/modules/$kernel/vmlinuz /boot/vmlinuz-$kernel
  ln /lib/modules/$kernel/System.map /boot/System.map-$kernel || cp /lib/modules/$kernel/System.map /boot/System.map-$kernel
  ln /lib/modules/$kernel/config /boot/config-$kernel || cp /lib/modules/$kernel/config /boot/config-$kernel
else
  echo 'You do not have rpm2cpio installed. Install rpm2cpio and try again.'
  exit -1
fi

if [ -f /boot/vmlinuz-$kernel ] && [ -f /boot/System.map-$kernel ] &&
   [ -f /boot/config-$kernel ] && file /boot/vmlinuz-$kernel | \
   grep -Fq 'Linux kernel x86 boot executable bzImage' && file /boot/System.map-$kernel | \
   grep -Fq 'ASCII text' && file /boot/config-$kernel | \
   grep -Fq 'Linux make config build file'
then
  echo 'Everything is OK. Finishing installation...'
  update-initramfs -ck $kernel
  grub-mkconfig -o /boot/grub/grub.cfg
  ln -fs boot/vmlinuz-$kernel /vmlinuz
  ln -fs boot/initrd.img-$kernel /initrd.img
  rm -f kernel-core-*.rpm kernel-modules-*.rpm
  echo 'Installation is complete! Type in (as root) "shutdown -r now" to restart.'
else
  echo 'Installation aborted due to missing or corrupted files! Try again!'
  exit -1
fi
