#!/bin/sh
# Copyright (c) 2021 Matheus Garcia.  All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer. 
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution. 
# 
# 3. Neither the name of the author nor the names of its contributors may be
#    used to endorse or promote products derived from this software without
#    specific prior written permission. 
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
host="http://archive.ubuntu.com/ubuntu/pool/main"
kver="`wget -O - $host/l/ | grep -o 'linux-hwe-[0-9].*' | sed -n '$s/\/.*//p' | dd bs=10 skip=1`"

[ "`whoami`" != "root" ] && echo Must be root. && exit -1

echo Do you wish to install the generic or lowlatency kernel?
read -r option

if echo $option | grep -Fqx generic
then
  kernel="`wget -O - $host/l/linux-hwe-$kver/ | grep -o 'linux-image-unsigned-[0-9].*-generic.*' | sed -n '$s/\.deb.*//p' | dd bs=21 skip=1`"
  wget $host/l/linux-hwe-$kver/linux-image-unsigned-$kernel.deb
  wget $host/l/linux-hwe-$kver/linux-modules-$kernel.deb
  wget $host/l/linux-hwe-$kver/linux-modules-extra-$kernel.deb
elif echo $option | grep -Fqx lowlatency
then
  kernel="`wget -O - $host/l/linux-hwe-$kver/ | grep -o 'linux-image-unsigned-[0-9].*-lowlatency.*' | sed -n '$s/\.deb.*//p' | dd bs=21 skip=1`"
  wget $host/l/linux-hwe-$kver/linux-image-unsigned-$kernel.deb
  wget $host/l/linux-hwe-$kver/linux-modules-$kernel.deb
  wget $host/l/linux-hwe-$kver/linux-modules-extra-$kernel.deb
else
  echo You must type in a valid kernel build.
  exit -1
fi

kpkg="data.tar"
ar -p linux-image-unsigned-$kernel.deb $kpkg | tar -C / -xvf -
ar -p linux-modules-$kernel.deb $kpkg.zst | zstd -dc | tar -C / -xvf - ./boot
ar -p linux-modules-$kernel.deb $kpkg.zst | zstd -dc | tar -C / -xvf - ./usr
ar -p linux-modules-$kernel.deb $kpkg.zst | zstd -dc | tar -C /usr -xvf - ./lib
ar -p linux-modules-extra-$kernel.deb $kpkg.zst | zstd -dc | tar -C /usr -xvf - ./lib
ar -p linux-modules-extra-$kernel.deb $kpkg.zst | zstd -dc | tar -C / -xvf - ./usr

if echo $option | grep -Fqx generic
then
  update-initramfs -ck "`wget -O - $host/l/linux-hwe-$kver/ | grep -o 'linux-image-unsigned-[0-9].*-generic.*' | sed -n '$s/-generic.*/-generic/p' | dd bs=21 skip=1`"
  grub-mkconfig -o /boot/grub/grub.cfg
elif echo $option | grep -Fqx lowlatency
then
  update-initramfs -ck "`wget -O - $host/l/linux-hwe-$kver/ | grep -o 'linux-image-unsigned-[0-9].*-lowlatency.*' | sed -n '$s/-lowlatency.*/-lowlatency/p' | dd bs=21 skip=1`"
  grub-mkconfig -o /boot/grub/grub.cfg
fi

rm -f linux-image-unsigned-*.deb linux-modules-*.deb
