#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

if ! echo `whoami` | grep -Fqx root
then
  echo Must be root.
  exit
fi

echo Do you wish to install the generic or lowlatency kernel?
read -r option

if echo $option | grep -Fqx generic
then
  wget http://archive.ubuntu.com/ubuntu/pool/main/l/linux-hwe-5.13/linux-image-unsigned-5.13.0-19-generic_5.13.0-19.19~20.04.1_amd64.deb
  wget http://archive.ubuntu.com/ubuntu/pool/main/l/linux-hwe-5.13/linux-modules-5.13.0-19-generic_5.13.0-19.19~20.04.1_amd64.deb
  wget http://archive.ubuntu.com/ubuntu/pool/main/l/linux-hwe-5.13/linux-modules-extra-5.13.0-19-generic_5.13.0-19.19~20.04.1_amd64.deb
fi

if echo $option | grep -Fqx lowlatency
then
  wget http://archive.ubuntu.com/ubuntu/pool/main/l/linux-hwe-5.13/linux-image-unsigned-5.13.0-19-lowlatency_5.13.0-19.19~20.04.1_amd64.deb
  wget http://archive.ubuntu.com/ubuntu/pool/main/l/linux-hwe-5.13/linux-modules-5.13.0-19-lowlatency_5.13.0-19.19~20.04.1_amd64.deb
  wget http://archive.ubuntu.com/ubuntu/pool/main/l/linux-hwe-5.13/linux-modules-extra-5.13.0-19-lowlatency_5.13.0-19.19~20.04.1_amd64.deb
else
  echo You must type in a valid kernel build.
  exit
fi

ar -p linux-image-unsigned-5.13.0-19-generic_5.13.0-19.19~20.04.1_amd64.deb | tar -C / -Jxvf -
ar -p linux-modules-5.13.0-19-generic_5.13.0-19.19~20.04.1_amd64.deb | tar -C / -Jxvf - ./boot
ar -p linux-modules-5.13.0-19-generic_5.13.0-19.19~20.04.1_amd64.deb | tar -C / -Jxvf - ./usr
ar -p linux-modules-5.13.0-19-generic_5.13.0-19.19~20.04.1_amd64.deb | tar -C /usr -Jxvf - ./lib
ar -p linux-modules-extra-5.13.0-19-generic_5.13.0-19.19~20.04.1_amd64.deb | tar -C /usr -Jxvf - ./lib
ar -p linux-modules-extra-5.13.0-19-generic_5.13.0-19.19~20.04.1_amd64.deb | tar -C / -Jxvf - ./usr

update-initramfs -ck 5.13.0-19-generic
grub-mkconfig -o /boot/grub/grub.cfg
